import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:archive/archive.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ExportService {
  // ─────────────────────────────────────────
  // PDF Export — uses built-in fonts (no internet needed)
  // ─────────────────────────────────────────
  static Future<void> exportPdf({
    required String title,
    required String content,
    required BuildContext context,
    Uint8List? signatureBytes,
  }) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final logoPath = prefs.getString('logoPath');
      
      final pdf = pw.Document();

      // Use built-in Helvetica — no network download needed
      final font = pw.Font.helvetica();
      final boldFont = pw.Font.helveticaBold();
      final obliqueFont = pw.Font.helveticaOblique();

      // Strip AI preamble and inline markdown for clean PDF output
      final cleanContent = _stripMarkdown(_cleanAiContent(content));

      pw.MemoryImage? logoImage;
      if (logoPath != null && logoPath.isNotEmpty) {
        final logoFile = File(logoPath);
        if (logoFile.existsSync()) {
          logoImage = pw.MemoryImage(logoFile.readAsBytesSync());
        }
      }

      pw.MemoryImage? signatureImage;
      if (signatureBytes != null && signatureBytes.isNotEmpty) {
        signatureImage = pw.MemoryImage(signatureBytes);
      }

      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            pageFormat: PdfPageFormat.a4,
            margin: const pw.EdgeInsets.symmetric(horizontal: 50, vertical: 40),
            buildBackground: (ctx) {
              if (logoImage != null) {
                return pw.FullPage(
                  ignoreMargins: true,
                  child: pw.Center(
                    child: pw.Opacity(
                      opacity: 0.04,
                      child: pw.Image(
                        logoImage,
                        width: 260,
                        height: 260,
                        fit: pw.BoxFit.contain,
                      ),
                    ),
                  ),
                );
              }
              return pw.SizedBox();
            },
          ),
          header: (ctx) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  if (logoImage != null)
                    pw.Row(
                      children: [
                        pw.Image(
                          logoImage,
                          height: 24,
                          width: 24,
                          fit: pw.BoxFit.contain,
                        ),
                        pw.SizedBox(width: 8),
                        pw.Text('KOMPLI',
                            style: pw.TextStyle(
                                font: boldFont,
                                fontSize: 14,
                                color: const PdfColor.fromInt(0xFF008751),
                                letterSpacing: 2)),
                      ],
                    )
                  else
                    pw.Text('KOMPLI',
                        style: pw.TextStyle(
                            font: boldFont,
                            fontSize: 16,
                            color: const PdfColor.fromInt(0xFF008751),
                            letterSpacing: 2)),
                  pw.Text('Legal Document',
                      style: pw.TextStyle(
                          font: obliqueFont,
                          fontSize: 10,
                          color: PdfColors.grey600)),
                ],
              ),
              pw.Divider(
                  color: const PdfColor.fromInt(0xFF008751), thickness: 1.5),
              pw.SizedBox(height: 6),
            ],
          ),
          footer: (ctx) => pw.Column(
            children: [
              pw.Divider(color: PdfColors.grey300, thickness: 0.5),
              pw.SizedBox(height: 4),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Generated by Kompli — Nigerian SME Legal Assistant',
                      style: pw.TextStyle(
                          font: obliqueFont,
                          fontSize: 8,
                          color: PdfColors.grey500)),
                  pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                      style: pw.TextStyle(
                          font: font, fontSize: 8, color: PdfColors.grey500)),
                ],
              ),
            ],
          ),
          build: (ctx) => [
            pw.Text(title.toUpperCase(),
                style: pw.TextStyle(
                    font: boldFont,
                    fontSize: 20,
                    color: const PdfColor.fromInt(0xFF001F3F),
                    letterSpacing: 0.5)),
            pw.SizedBox(height: 6),
            pw.Divider(color: PdfColors.grey400, thickness: 0.5),
            pw.SizedBox(height: 18),
            ..._buildPdfContent(cleanContent, font, boldFont),
            pw.SizedBox(height: 48),
            pw.Divider(color: PdfColors.grey600),
            pw.SizedBox(height: 16),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _signatureBlock(font, 'Party A Signature', signatureImage: signatureImage),
                _signatureBlock(font, 'Party B Signature'),
              ],
            ),
          ],
        ),
      );

      await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: '${_sanitizeFilename(title)}_Kompli.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF export failed: $e'),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    }
  }

  // ─────────────────────────────────────────
  // DOCX Export — builds a proper .docx (OOXML) file
  // ─────────────────────────────────────────
  static Future<void> exportDocx({
    required String title,
    required String content,
    required BuildContext context,
  }) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final companyName = prefs.getString('companyName');
      final rcNumber = prefs.getString('rcNumber');
      final tin = prefs.getString('tin');
      final address = prefs.getString('address');
      final industry = prefs.getString('industry');

      // Strip AI preamble before building DOCX
      final cleanContent = _cleanAiContent(content);
      final bytes = _buildDocx(
        title,
        cleanContent,
        companyName: companyName,
        rcNumber: rcNumber,
        tin: tin,
        address: address,
        industry: industry,
      );

      // Write to temp file
      final dir = await getTemporaryDirectory();
      final filename = '${_sanitizeFilename(title)}_Kompli.docx';
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(bytes);

      // Share the file
      await Share.shareXFiles(
        [XFile(file.path, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')],
        subject: title,
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('DOCX export failed: $e'),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    }
  }

  // ─────────────────────────────────────────
  // Internal helpers
  // ─────────────────────────────────────────

  static List<pw.Widget> _buildPdfContent(
      String content, pw.Font font, pw.Font boldFont) {
    final widgets = <pw.Widget>[];
    for (final line in content.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isEmpty) {
        widgets.add(pw.SizedBox(height: 8));
      } else if (trimmed.startsWith('###')) {
        widgets.add(pw.Text(trimmed.replaceAll('#', '').trim(),
            style: pw.TextStyle(
                font: boldFont,
                fontSize: 13,
                color: const PdfColor.fromInt(0xFF001F3F))));
        widgets.add(pw.SizedBox(height: 4));
      } else if (trimmed.startsWith('##')) {
        widgets.add(pw.SizedBox(height: 6));
        widgets.add(pw.Text(trimmed.replaceAll('#', '').trim(),
            style: pw.TextStyle(
                font: boldFont,
                fontSize: 15,
                color: const PdfColor.fromInt(0xFF001F3F))));
        widgets.add(pw.SizedBox(height: 4));
      } else if (trimmed.startsWith('#')) {
        widgets.add(pw.SizedBox(height: 8));
        widgets.add(pw.Text(trimmed.replaceAll('#', '').trim(),
            style: pw.TextStyle(
                font: boldFont,
                fontSize: 17,
                color: const PdfColor.fromInt(0xFF001F3F))));
        widgets.add(pw.SizedBox(height: 6));
      } else {
        widgets.add(pw.Text(trimmed,
            style: pw.TextStyle(font: font, fontSize: 11, lineSpacing: 4)));
        widgets.add(pw.SizedBox(height: 3));
      }
    }
    return widgets;
  }

  static pw.Widget _signatureBlock(pw.Font font, String label, {pw.MemoryImage? signatureImage}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        if (signatureImage != null)
          pw.Container(
            height: 40,
            width: 100,
            margin: const pw.EdgeInsets.only(bottom: 4),
            alignment: pw.Alignment.bottomLeft,
            child: pw.Image(signatureImage, fit: pw.BoxFit.contain),
          )
        else
          pw.SizedBox(height: 44),
        pw.Container(width: 175, height: 1, color: PdfColors.grey700),
        pw.SizedBox(height: 4),
        pw.Text(label,
            style:
                pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey600)),
        pw.Text('Date: _______________',
            style:
                pw.TextStyle(font: font, fontSize: 9, color: PdfColors.grey600)),
      ],
    );
  }

  static Uint8List _buildDocx(
    String title,
    String content, {
    String? companyName,
    String? rcNumber,
    String? tin,
    String? address,
    String? industry,
  }) {
    final documentXml = _buildDocumentXml(
      title,
      content,
      companyName: companyName,
      rcNumber: rcNumber,
      tin: tin,
      address: address,
      industry: industry,
    );

    // All five required OOXML files
    const contentTypes = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>''';

    const rootRels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
    Target="word/document.xml"/>
</Relationships>''';

    const docRels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
    Target="styles.xml"/>
</Relationships>''';

    const styles = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
          xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
        <w:sz w:val="24"/>
      </w:rPr>
    </w:rPrDefault>
  </w:docDefaults>
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/>
    <w:pPr><w:outlineLvl w:val="0"/></w:pPr>
    <w:rPr>
      <w:b/>
      <w:color w:val="001F3F"/>
      <w:sz w:val="40"/>
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="heading 2"/>
    <w:pPr><w:outlineLvl w:val="1"/></w:pPr>
    <w:rPr>
      <w:b/>
      <w:color w:val="001F3F"/>
      <w:sz w:val="32"/>
    </w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading3">
    <w:name w:val="heading 3"/>
    <w:pPr><w:outlineLvl w:val="2"/></w:pPr>
    <w:rPr>
      <w:b/>
      <w:color w:val="001F3F"/>
      <w:sz w:val="28"/>
    </w:rPr>
  </w:style>
</w:styles>''';

    // Build zip using utf8 encoding for all XML text
    final archive = Archive();

    void add(String name, String xml) {
      final bytes = utf8.encode(xml);
      archive.addFile(ArchiveFile(name, bytes.length, bytes));
    }

    add('[Content_Types].xml', contentTypes);
    add('_rels/.rels', rootRels);
    add('word/document.xml', documentXml);
    add('word/styles.xml', styles);
    add('word/_rels/document.xml.rels', docRels);

    final zipped = ZipEncoder().encode(archive);
    return Uint8List.fromList(zipped);
  }

  static String _buildDocumentXml(
    String title,
    String content, {
    String? companyName,
    String? rcNumber,
    String? tin,
    String? address,
    String? industry,
  }) {
    final body = StringBuffer();

    // Title
    body.write(_para(title.toUpperCase(),
        bold: true, size: 40, color: '001F3F', center: true));
    body.write(_emptyPara());

    // Letterhead / Branding
    if (companyName != null && companyName.trim().isNotEmpty) {
      body.write(_para(companyName.trim().toUpperCase(),
          bold: true, size: 28, color: '001F3F', center: true));

      final details = <String>[];
      if (rcNumber != null && rcNumber.trim().isNotEmpty) {
        details.add('RC: ${rcNumber.trim()}');
      }
      if (tin != null && tin.trim().isNotEmpty) {
        details.add('TIN: ${tin.trim()}');
      }
      if (industry != null && industry.trim().isNotEmpty) {
        details.add('Industry: ${industry.trim()}');
      }

      if (details.isNotEmpty) {
        body.write(_para(details.join('  |  '),
            size: 16, color: '008751', center: true));
      }

      if (address != null && address.trim().isNotEmpty) {
        body.write(_para(address.trim(),
            size: 14, color: '555555', center: true));
      }

      body.write(_para('─' * 55, color: '008751', center: true));
      body.write(_emptyPara());
    } else {
      // Fallback simple branding
      body.write(_para('Generated by Kompli — Nigerian SME Legal Assistant',
          size: 18, color: '008751', center: true, italic: true));
      body.write(_emptyPara());
    }

    // Content lines
    for (final rawLine in content.split('\n')) {
      final line = rawLine.trim();
      if (line.isEmpty) {
        body.write(_emptyPara());
      } else if (line.startsWith('### ')) {
        body.write(_para(line.substring(4),
            bold: true, size: 26, color: '001F3F', styleId: 'Heading3'));
      } else if (line.startsWith('## ')) {
        body.write(_para(line.substring(3),
            bold: true, size: 32, color: '001F3F', styleId: 'Heading2'));
      } else if (line.startsWith('# ')) {
        body.write(_para(line.substring(2),
            bold: true, size: 40, color: '001F3F', styleId: 'Heading1'));
      } else if (line.startsWith('**') && line.endsWith('**') && line.length > 4) {
        body.write(_para(line.substring(2, line.length - 2), bold: true));
      } else {
        // Strip inline markdown bold/italic markers properly
        final clean = line
            .replaceAllMapped(RegExp(r'\*\*(.+?)\*\*'), (m) => m.group(1) ?? '')
            .replaceAllMapped(RegExp(r'\*(.+?)\*'), (m) => m.group(1) ?? '');
        body.write(_para(clean));
      }
    }

    // Signature section
    body.write(_emptyPara());
    body.write(_emptyPara());
    body.write(_para('─' * 35 + '          ' + '─' * 35));
    body.write(_para('Party A Signature' + '                                    ' + 'Party B Signature'));
    body.write(_para('Date: _______________' + '                               ' + 'Date: _______________'));

    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <w:body>
$body
    <w:sectPr>
      <w:pgSz w:w="11906" w:h="16838"/>
      <w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"
               w:header="708" w:footer="708" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>''';
  }

  static String _para(
    String text, {
    bool bold = false,
    bool italic = false,
    int size = 24,
    String? color,
    bool center = false,
    String? styleId,
  }) {
    final pPr = StringBuffer();
    if (styleId != null) {
      pPr.write('<w:pStyle w:val="$styleId"/>');
    }
    if (center) {
      pPr.write('<w:jc w:val="center"/>');
    }

    final rPr = StringBuffer();
    if (bold) rPr.write('<w:b/>');
    if (italic) rPr.write('<w:i/>');
    if (color != null) rPr.write('<w:color w:val="$color"/>');
    rPr.write('<w:sz w:val="$size"/>');
    rPr.write('<w:szCs w:val="$size"/>');

    final escapedText = _escapeXml(text);

    return '''    <w:p>
      <w:pPr>$pPr<w:spacing w:after="120"/></w:pPr>
      <w:r>
        <w:rPr>$rPr</w:rPr>
        <w:t xml:space="preserve">$escapedText</w:t>
      </w:r>
    </w:p>
''';
  }

  static String _emptyPara() => '''    <w:p>
      <w:pPr><w:spacing w:after="80"/></w:pPr>
      <w:r><w:t></w:t></w:r>
    </w:p>
''';

  static String _escapeXml(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&apos;');

  /// Strips inline markdown bold/italic for plain-text contexts (PDF body, etc.).
  static String _stripMarkdown(String text) => text
      .replaceAllMapped(RegExp(r'\*\*(.+?)\*\*'), (m) => m.group(1) ?? '')
      .replaceAllMapped(RegExp(r'\*(.+?)\*'), (m) => m.group(1) ?? '')
      .replaceAllMapped(RegExp(r'__(.+?)__'), (m) => m.group(1) ?? '');

  /// Removes any AI preamble (conversational intro) before the first heading.
  static String _cleanAiContent(String text) {
    final lines = text.split('\n');
    // Find the first line that looks like a heading or all-caps title
    final firstDocLine = lines.indexWhere((l) {
      final t = l.trim();
      return t.startsWith('#') ||
          (t.length > 4 && t == t.toUpperCase() && RegExp(r'[A-Z]').hasMatch(t));
    });
    if (firstDocLine > 0) {
      return lines.sublist(firstDocLine).join('\n');
    }
    return text;
  }

  static String _sanitizeFilename(String name) =>
      name.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
}
