// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4rGhroHkaPKcXdFH4oCnvCVSDil2N78',
    appId: '1:1062107981168:web:e145788deacc38bfabdbb5',
    messagingSenderId: '1062107981168',
    projectId: 'kompli-fab00',
    authDomain: 'kompli-fab00.firebaseapp.com',
    storageBucket: 'kompli-fab00.firebasestorage.app',
    measurementId: 'G-1BT7X34S04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvjpVSb3Ugy8MK4CXiyoFNZKdCXovlpU',
    appId: '1:1062107981168:android:04a65854212c3558abdbb5',
    messagingSenderId: '1062107981168',
    projectId: 'kompli-fab00',
    storageBucket: 'kompli-fab00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5AOPi3fbn4FKjQVfiPVcYU9RYEkUK75U',
    appId: '1:1062107981168:ios:ca90a21d263c7111abdbb5',
    messagingSenderId: '1062107981168',
    projectId: 'kompli-fab00',
    storageBucket: 'kompli-fab00.firebasestorage.app',
    iosBundleId: 'com.lexnaija.kompli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5AOPi3fbn4FKjQVfiPVcYU9RYEkUK75U',
    appId: '1:1062107981168:ios:ca90a21d263c7111abdbb5',
    messagingSenderId: '1062107981168',
    projectId: 'kompli-fab00',
    storageBucket: 'kompli-fab00.firebasestorage.app',
    iosBundleId: 'com.lexnaija.kompli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4rGhroHkaPKcXdFH4oCnvCVSDil2N78',
    appId: '1:1062107981168:web:ade92fa781b1c0a0abdbb5',
    messagingSenderId: '1062107981168',
    projectId: 'kompli-fab00',
    authDomain: 'kompli-fab00.firebaseapp.com',
    storageBucket: 'kompli-fab00.firebasestorage.app',
    measurementId: 'G-7M94X699RG',
  );
}
